### ISSUE TITLE
Invalid transition exception with short cycle count in findmax

### ISSUE THREAD

**Issue by jshook** [engineblock/engineblock#113]
java.lang.RuntimeException: Invalid transition from Finished to Starting
        at io.engineblock.activityimpl.SlotStateTracker.enterState(SlotStateTracker.java:62)
        at io.engineblock.core.ActivityExecutor.lambda$adjustToIntendedActivityState$5                     (ActivityExecutor.java:238)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)

**Comment by jshook** [comment]
No recent reports of this, and other improvements have been made around state management. Closing until/unless new reports occur.
