### ISSUE TITLE
NPE during early reporting interval, thrown from GraphiteReporter#report

### ISSUE THREAD

**Issue by jshook** [engineblock/engineblock#169]
The gauge implementation for getWaitTime should always return a valid value.

07:15:55.681 [metrics-graphite-reporter-1-thread-1] ERROR c.codahale.metrics.ScheduledReporter - Exception thrown from GraphiteReporter#report. Exception was suppressed.
java.lang.NullPointerException: null
        at io.engineblock.activityapi.ratelimits.HybridRateLimiter.getWaitTime(HybridRateLimiter.java:133)
        at io.engineblock.activityapi.ratelimits.HybridRateLimiter.getTotalWaitTime(HybridRateLimiter.java:128)
        at io.engineblock.activityapi.ratelimits.RateLimiters$WaitTimeGauge.getValue(RateLimiters.java:56)
        at io.engineblock.activityapi.ratelimits.RateLimiters$WaitTimeGauge.getValue(RateLimiters.java:46)
        at com.codahale.metrics.graphite.GraphiteReporter.reportGauge(GraphiteReporter.java:343)
        at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:243)
        at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:243)
        at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:182)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)

**Comment by jshook** [comment]
Fixed in master.
