### ISSUE TITLE
Ranging error on AsciiGraph

### ISSUE THREAD

**Issue by jshook** [engineblock/engineblock#171]
I believe this one was with the asciigraph enabled, but not explicitly by the user.

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 13 out of bounds for char[12]
at java.base/java.lang.System.arraycopy(Native Method)
at com.mitchtalmadge.asciidata.graph.ASCIIGraph.drawTicksAndAxis(ASCIIGraph.java:181)
at com.mitchtalmadge.asciidata.graph.ASCIIGraph.plot(ASCIIGraph.java:157)
at io.engineblock.metrics.HistoLogChartGenerator.generateChartFromHistoLog(HistoLogChartGenerator.java:63)
at io.engineblock.metrics.HistoIntervalLogger.closeMetrics(HistoIntervalLogger.java:140)
at io.engineblock.metrics.ActivityMetrics.closeMetrics(ActivityMetrics.java:266)
at io.engineblock.cli.EBCLI.run(EBCLI.java:181)
at com.datastax.ebdse.EBDSE.main(EBDSE.java:10)

**Comment by phact** [comment]
1) the charts get turned on when log-histograms is specified
we should keep them off by default
2) the ascii charts are blowing up since it's a tiny run (ddl only)
need to look into why this is

**Comment by jshook** [comment]
This is fixed in master.
