### ISSUE TITLE
Verify motor control sanity with short activities

### ISSUE THREAD

**Issue by jshook** [engineblock/engineblock#4]
The motor control logic should probably be collapsed into the motor implementation. The state model does not currently like it when the motor decides to go into "finished" state.

Basically, the motor control state needs to be made compatible with all async event changes that affect it. Keeping a strict state model is desired if possible without making it too complex.

**Comment by jshook** [comment]
from previous ticket by @tupshin 

stack trace to ease debugability:
java -jar em.jar ../bin/sanitycheck.js
and...
22:48:38.813 [main] DEBUG c.m.load.core.ActivityExecutor - >post-adjust->[S>,S>,S>,S>,S>,S>,S>,S>,S>,S>]
waiting 2000 ms
waited
22:48:41.000 [main] INFO c.m.load.activityapi.ParameterMap - parameter interval put to 1000
22:48:41.001 [main] DEBUG c.m.load.activityapi.ParameterMap - calling 1 listeners.
22:48:41.001 [main] INFO c.m.load.activityapi.ParameterMap - calling listener:ActivityExecutor~test
22:48:41.001 [main] DEBUG c.m.load.core.ActivityExecutor - >-pre-adjust->[​.,​.,​.,​.,​.,​.,​.,​.,​.,​.]
Exception in thread "test:011" java.lang.RuntimeException: Unable to transition motor controller Initialized --> Started: current state:Stopped
at com.metawiring.load.activitycore.MotorController.transitionOrException(MotorController.java:85)
at com.metawiring.load.activitycore.MotorController.signalStarted(MotorController.java:47)
at com.metawiring.load.activitycore.CoreMotor.run(CoreMotor.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
