### ISSUE TITLE
thread-safety error for concurrent iterator access in StatsIntervalLogger

### ISSUE THREAD

**Issue by jshook** [engineblock/engineblock#97]
Exception in thread "HistoLogger:.*:histostats.csv:10" java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
        at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:744)
        at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:742)
        at io.engineblock.metrics.StatsIntervalLogger.run(StatsIntervalLogger.java:109)
        at io.engineblock.metrics.PeriodicRunnable.run(PeriodicRunnable.java:51)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jshook** [comment]
This was fixed by using CopyOnWriteArray and concurrent data structures in some places.
